export const FIELD_NOT_RETURN = '-createdAt -updatedAt -password'

export const ROLES = { ADMIN: 'ADMIN', STAFF: 'STAFF' }

export const PERMISSIONS = {
  VIEW_USER: 'XEM_USER',
  VIEW_USER_DETAIL: 'XEM_USER_DETAIL',
  EDIT_USER: 'SUA_USER',
  DELETE_USER: 'XOA_USER',
  ASSIGN_ROLE: 'PHAN_QUYEN_USER',

  VIEW_LEAD: 'XEM_LEAD',
  CREATE_LEAD: 'TAO_LEAD',
  EDIT_LEAD: 'SUA_LEAD',
  DELETE_LEAD: 'XOA_LEAD',
  ASSIGN_LEAD: 'GAN_LEAD',
  UPDATE_LEAD_STATUS: 'CAP_NHAT_TRANG_THAI_LEAD',

  VIEW_FOLLOWUP: 'XEM_FOLLOWUP',
  CREATE_FOLLOWUP: 'TAO_FOLLOWUP',
  EDIT_FOLLOWUP: 'SUA_FOLLOWUP',
  DELETE_FOLLOWUP: 'XOA_FOLLOWUP',
  COMPLETE_FOLLOWUP: 'HOAN_THANH_FOLLOWUP',

  VIEW_DASHBOARD: 'XEM_DASHBOARD',
  VIEW_EFFICIENCY: 'XEM_HIEU_SUAT'
}
